### PR TITLE
TEM-6: Upload encryption, download decryption

### PR DESCRIPTION
**Pull request by bobheadxi**
## :construction_worker: Purpose

Add option to encrypt and decrypt uploads

## :rocket: Changes

- pass a passphrase on advanced file uploads to encrypt it using the new [RTradeLtd/crypto](https://github.com/RTradeLtd/crypto)
- pass a decrypt key on download requests to decrypt file using [RTradeLtd/crypto](https://github.com/RTradeLtd/crypto)
- various other minor cleanup

## :warning: Breaking Changes

the get uploads API is now GET, instead of POST

https://github.com/RTradeLtd/Temporal/compare/upload/encrypt?expand=1#diff-604f4192deea5adf9c159e5f88f64630R203

## todo

- [ ] more robust testing
- [x] polish [RTradeLtd/crypto](https://github.com/RTradeLtd/crypto) and put out a tagged release to vendor

### CODE REVIEW

**Comment by postables** [comment]
https://media.giphy.com/media/3oKIP96VswizmYabPa/giphy.gif

Initial glance looks WICKED, will give it a full test and review tomorrow :ok_hand:

**Comment by postables** [comment]
Hmm I can't appear to download the file via content hash and decrypt, nothing happens.
Tried downloading manually and running the crypto tool which didnt seem to work:
```
rtrade@ipfs-node-2:~/t$ temporal-crypto decrypt QmYjDfHsQMmiJm2M3As2GksLPgzcuqW4KFba6rHL9yCTBh 
rtrade@ipfs-node-2:~/t$ ls -la
total 9364
drwxrwxr-x  2 rtrade rtrade    4096 Oct 10 03:06 .
drwxr-xr-x 14 rtrade rtrade    4096 Oct 10 03:06 ..
-rw-rw-r--  1 rtrade rtrade 9576504 Oct 10 03:06 QmYjDfHsQMmiJm2M3As2GksLPgzcuqW4KFba6rHL9yCTBh
```

**Comment by postables** [comment]
Looks like crypto is just saving to the same file. I tested, and was able to decrypt and play the video i tested out.

**Comment by bobheadxi** [comment]
I've opened up https://github.com/RTradeLtd/crypto/pull/1 to resolve the weird output of the decrypt tool

**Pull request merged**
